# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_subtitle', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
