# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20160527_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ['the_order'], 'verbose_name': 'Navigation Link', 'verbose_name_plural': 'Navigation Links'},
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='link',
            field=models.URLField(),
        ),
    ]
