# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20160527_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='navigationlink',
            old_name='the_order',
            new_name='order',
        ),
    ]
