# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20160527_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
