# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20160526_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='still_active',
        ),
        migrations.AlterField(
            model_name='education',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
