# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160514_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.CharField(max_length=200)),
                ('alt_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='gallerypost',
            name='tags',
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.GalleryPost'),
        ),
    ]
