# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160514_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallerypost',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='gallerypost',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='gallerypost',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='gallerypost',
            name='style',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=portfolio.models.PathAndRename('images/portfolio/'), width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='client',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='client_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='credit',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='medium',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='project',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.Tag'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
