# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160516_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.PathAndRename('website/images/portfolio/')),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name=portfolio.models.PathAndRename('website/images/portfolio/thumbnails/')),
        ),
    ]
