# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160519_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_per_page', models.SmallIntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
