# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20160526_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypost',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
